# Your presentation title
title: Jekyll and Reveal.js

# Your presentation description (optional)
description: A framework for easily creating beautiful presentations using HTML

# Your name (optional)
author: jekyll-revealjs contributors

# The Reveal theme
reveal_theme: at.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: assets/css/

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: assets/reveal.js/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

background_color: "#222B5E"

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme